apiVersion: v1
kind: ConfigMap
metadata:
  name: statsd-aggregator-cfg
data:
  aggregator.cfg: |
    listen_port = 8125;
    log_level = 2;
    downstream_flush_interval = 1.0;

    downstreams = (
      {
        host = "host.com";
        sink_port = 9125;
        healthcheck_port = 0;
      }
    );
