apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: statsd-aggregator
  labels:
     app: statsd
     name: statsd-aggregator
     tier: aux-service
spec:
  selector:
  matchLabels:
    name: statsd-aggregator
    tier: aux-service
  template:
    metadata:
      name: statsd-aggregator
      labels:
        name: statsd-aggregator
        tier: aux-service
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: statsd-aggregator
        image: ark0/statsd-aggregator:rc0
        command: ["./statsd-aggregator"]
        args: ["-c","/etc/aggregator/aggregator.cfg"]
        resources:
          requests:
            cpu: 750m
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 16Mi
        volumeMounts:
        - name: statsd-aggregator-cfg-volume
          mountPath: /etc
        ports:
          - containerPort: 8125
      terminationGracePeriodSeconds: 10
      volumes:
      - name: statsd-aggregator-cfg-volume
        configMap:
           name: statsd-aggregator-cfg
